In [7]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().resolve()

if BASE_DIR.name == "src":
    BASE_DIR = BASE_DIR.parent

PROCESSED_DIR = BASE_DIR / "data" / "processed"

print("BASE_DIR:", BASE_DIR)
print("PROCESSED_DIR:", PROCESSED_DIR)

dia = pd.read_csv(
    PROCESSED_DIR / "dia_products.csv"
)

mercadona = pd.read_csv(
    PROCESSED_DIR / "mercadona_products.csv"
)

aldi = pd.read_csv(
    PROCESSED_DIR / "aldi_products.csv"
)

print("DIA:", len(dia))
print("Mercadona:", len(mercadona))
print("ALDI:", len(aldi))

BASE_DIR: C:\Users\Giuliana Galassi\OneDrive\Documentos\uc3m\4TO\WEB ANALYTICS\supermarket_project
PROCESSED_DIR: C:\Users\Giuliana Galassi\OneDrive\Documentos\uc3m\4TO\WEB ANALYTICS\supermarket_project\data\processed
DIA: 2235
Mercadona: 895
ALDI: 773

In [8]:
from normalize import normalize_units

dia = normalize_units(dia)
mercadona = normalize_units(mercadona)
aldi = normalize_units(aldi)

In [12]:
COMMON_COLUMNS = [
    "supermarket",
    "searched_item",
    "name",
    "price",
    "price_per_unit",
    "unit",
]
dia_compare = dia[COMMON_COLUMNS].copy()
mercadona_compare = mercadona[COMMON_COLUMNS].copy()
aldi_compare = aldi[COMMON_COLUMNS].copy()

In [13]:
dia_compare = dia[COMMON_COLUMNS].copy()
mercadona_compare = mercadona[COMMON_COLUMNS].copy()
aldi_compare = aldi[COMMON_COLUMNS].copy()

all_products = pd.concat(
    [
        dia_compare,
        mercadona_compare,
        aldi_compare,
    ],
    ignore_index=True
)

In [14]:
print(
    all_products["supermarket"]
    .value_counts()
)

print("\nUnidades:")
print(
    all_products["unit"]
    .value_counts()
)

print("\nBúsquedas:")
print(
    all_products["searched_item"]
    .value_counts()
)

supermarket
DIA          2235
Mercadona     895
ALDI          773
Name: count, dtype: int64

Unidades:
unit
KILO         2466
LITRO        1167
UNIDAD        190
LAVADO         45
DOCENA         10
METRO           8
ROLLO           4
BOLSITA         4
SERVICIO        2
CAPSULA         2
SOBRE           1
PASTILLA        1
MONODOSIS       1
PANUELO         1
TOALLITA        1
Name: count, dtype: int64[pyarrow]

Búsquedas:
searched_item
leche              559
agua               393
pan                390
aceite             338
arroz              297
yogur              285
queso              242
tomate             209
pollo              183
pasta              169
zumo               135
atún               127
detergente         115
manzana            101
salmón              80
carne picada        72
papel higiénico     66
plátano             63
huevos              61
garbanzos           18
Name: count, dtype: int64

In [15]:
leche = all_products[
    all_products["searched_item"] == "leche"
].copy()

display(
    leche[
        [
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ]
    .sort_values(
        ["unit", "price_per_unit"]
    )
)

,supermarket,name,price,price_per_unit,unit
3187,ALDI,Cápsulas de café con leche,3.17,0.20,CAPSULA
3189,ALDI,Cápsulas de café con leche descafeinado,3.17,0.20,CAPSULA
10,DIA,Huevos medianos M Dia 24 unidades,5.25,2.63,DOCENA
335,DIA,Huevos medianos M de gallinas criadas en suelo...,2.85,2.85,DOCENA
342,DIA,Huevos grandes L Dia 18 unidades,4.39,2.93,DOCENA
...,...,...,...,...,...
253,DIA,Cápsulas de cafe con leche Dolce Gusto 16 unid...,4.95,0.31,UNIDAD
265,DIA,Cápsulas de café con leche intenso Dolce Gusto...,4.99,0.31,UNIDAD
258,DIA,Cápsulas de café con leche descafeinado Dolce ...,5.19,0.32,UNIDAD
262,DIA,Cápsulas de café con leche Marcilla 16 unidades,5.89,0.37,UNIDAD
278,DIA,Barrita de galleta y chocolate con leche Nestl...,0.99,0.99,UNIDAD

In [16]:
cheapest_by_supermarket = (
    all_products
    .sort_values("price_per_unit")
    .groupby(
        [
            "searched_item",
            "supermarket",
            "unit",
        ],
        as_index=False
    )
    .first()
)

display(cheapest_by_supermarket)

,searched_item,supermarket,unit,name,price,price_per_unit
0,aceite,ALDI,KILO,Altramuces,1.45,3.82
1,aceite,ALDI,LITRO,Vinagre de vino blanco,0.62,0.62
2,aceite,DIA,KILO,Sal gruesa Dia 1 Kg,0.40,0.40
3,aceite,DIA,LITRO,Vinagre de vino blanco Aliña tu Dia 1 L,0.65,0.65
4,aceite,DIA,UNIDAD,Bandas de cera faciales con aloe vera y aceite...,1.00,0.06
...,...,...,...,...,...,...
127,zumo,ALDI,LITRO,Bebida Bahamas,1.19,0.60
128,zumo,DIA,KILO,Naranja de zumo 3 Kg,5.99,2.00
129,zumo,DIA,LITRO,Zumo de melocotón y uva Dia Saborfera 1 L,0.75,0.75
130,zumo,Mercadona,KILO,Naranjas,5.85,1.95
131,zumo,Mercadona,LITRO,Bebida Bahamas Hacendado,1.25,0.62

In [17]:
cheapest_overall = (
    all_products
    .sort_values("price_per_unit")
    .groupby(
        [
            "searched_item",
            "unit",
        ],
        as_index=False
    )
    .first()
)

display(
    cheapest_overall[
        [
            "searched_item",
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ]
)

,searched_item,supermarket,name,price,price_per_unit,unit
0,aceite,Mercadona,Sal gruesa Hacendado,0.40,0.40,KILO
1,aceite,ALDI,Vinagre de vino blanco,0.62,0.62,LITRO
2,aceite,DIA,Bandas de cera faciales con aloe vera y aceite...,1.00,0.06,UNIDAD
3,agua,ALDI,Aguacate,1.09,4.80,KILO
4,agua,Mercadona,Agua mineral grande Aguadoy,0.95,0.12,LITRO
...,...,...,...,...,...,...
59,tomate,Mercadona,Pizzas tomate y queso Hacendado ultracongeladas,2.40,1.20,UNIDAD
60,yogur,ALDI,Yogur de sabores,1.72,1.15,KILO
61,yogur,ALDI,Kéfir ecológico con limón,1.69,3.38,LITRO
62,zumo,Mercadona,Naranjas,5.85,1.95,KILO
63,zumo,ALDI,Bebida Bahamas,1.19,0.60,LITRO

In [18]:
display(
    all_products[
        all_products["searched_item"] == "leche"
    ][
        [
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ].head(50)
)

,supermarket,name,price,price_per_unit,unit
0,DIA,Leche semidesnatada Dia Láctea pack 6 x 1 L,5.04,0.84,LITRO
1,DIA,Leche entera Dia Láctea pack 6 x 1 L,5.76,0.96,LITRO
2,DIA,Leche semidesnatada sin lactosa Dia Láctea pac...,5.64,0.94,LITRO
3,DIA,Leche semidesnatada Dia Láctea 1 L,0.84,0.84,LITRO
4,DIA,Leche desnatada Dia Láctea pack 6 x 1 L,4.92,0.82,LITRO
5,DIA,Leche entera Dia Láctea 1 L,0.96,0.96,LITRO
6,DIA,Leche entera Dia Láctea 3 x 200 ml,0.92,1.53,LITRO
7,DIA,Leche desnatada sin lactosa Dia Láctea pack 6 ...,5.46,0.91,LITRO
8,DIA,Leche semidesnatada sin lactosa Dia Láctea 1 L,0.94,0.94,LITRO
9,DIA,Leche semidesnatada Asturiana pack 6 x 1 L,7.02,1.17,LITRO
10,DIA,Huevos medianos M Dia 24 unidades,5.25,2.63,DOCENA
11,DIA,Leche entera pasteurizada Dia Láctea 1 L,1.15,1.15,LITRO
12,DIA,Leche entera Asturiana pack 6 x 1 L,7.74,1.29,LITRO
13,DIA,Leche desnatada Dia Láctea 1 L,0.82,0.82,LITRO
14,DIA,Bebida de avena Dia Vegedia 1 L,0.95,0.95,LITRO
15,DIA,Leche semidesnatada Dia Láctea botella 1.5 L,1.35,0.90,LITRO
16,DIA,Leche entera sin lactosa Dia Láctea pack 6 x 1 L,6.18,1.03,LITRO
17,DIA,Batido de cacao 90% leche Dia Láctea 6 x 200 ml,1.75,1.46,LITRO
18,DIA,Leche desnatada sin lactosa Dia Láctea 1 L,0.91,0.91,LITRO
19,DIA,Leche semidesnatada Asturiana pack 6 x 1.5 L,10.74,1.19,LITRO
20,DIA,Leche semidesnatada pasteurizada Dia Láctea 1 L,1.09,1.09,LITRO
21,DIA,Leche entera Asturiana pack 6 x 1.5 L,11.82,1.31,LITRO
22,DIA,Leche semidesnatada sin lactosa Dia Láctea 3 x...,0.95,1.58,LITRO
23,DIA,Leche entera Dia Láctea botella 1.5 L,1.49,0.99,LITRO
24,DIA,Leche desnatada Asturiana pack 6 x 1 L,6.78,1.13,LITRO
25,DIA,Leche semidesnatada Asturiana 1 L,1.17,1.17,LITRO
26,DIA,Leche condensada Dia Láctea 450 g,2.35,5.22,KILO
27,DIA,Leche semidesnatada sin lactosa Asturiana pack...,8.04,1.34,LITRO
28,DIA,Leche desnatada sin lactosa alta en proteínas ...,1.35,1.35,LITRO
29,DIA,Leche entera sin lactosa Dia Láctea 1 L,1.03,1.03,LITRO
30,DIA,Leche entera Asturiana 1 L,1.29,1.29,LITRO
31,DIA,Nata para cocinar textura espesa Dia Láctea 50...,1.55,3.10,LITRO
32,DIA,Leche semidesnatada calcio Dia Láctea pack 6 x...,6.30,1.05,LITRO
33,DIA,Nata para cocinar 18% M.G. Dia Láctea 3 x 200 ml,1.85,3.08,LITRO
34,DIA,Leche semidesnatada Dia Láctea pack 6 x 1.5 L,8.10,0.90,LITRO
35,DIA,Pan de leche El Molino de Dia 350 g,1.35,3.86,KILO
36,DIA,Leche condensada Dia Láctea 1 Kg,3.35,3.35,KILO
37,DIA,Chocolate con leche Nestlé Extrafino 125 g,1.50,12.00,KILO
38,DIA,Leche entera Dia Láctea pack 6 x 1.5 L,8.94,0.99,LITRO
39,DIA,Arroz con leche Dia Caprichoso 4 x 125 g,1.25,2.50,KILO
40,DIA,Mousse de chocolate con leche Dia Caprichoso 4...,1.15,4.79,KILO
41,DIA,Leche entera Pascual pack 6 x 1 L,7.74,1.29,LITRO
42,DIA,Bebida de almendras 0% azúcares Dia Vegedia 1 L,1.49,1.49,LITRO
43,DIA,Leche semidesnatada Asturiana botella 1.5 L,1.79,1.19,LITRO
44,DIA,Leche desnatada Asturiana pack 6 x 1.5 L,10.38,1.15,LITRO
45,DIA,Leche semidesnatada Asturiana pack 6 x 2.2 L,13.62,1.03,LITRO
46,DIA,Galletas cubiertas de chocolate con leche Gall...,1.35,9.00,KILO
47,DIA,Leche semidesnatada Pascual pack 6 x 1 L,7.14,1.19,LITRO
48,DIA,Leche desnatada sin lactosa Asturiana 1 L,1.28,1.28,LITRO
49,DIA,Leche semidesnatada calcio Dia Láctea 1 L,1.05,1.05,LITRO