In [11]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().resolve()

if BASE_DIR.name == "src":
    BASE_DIR = BASE_DIR.parent

PROCESSED_DIR = BASE_DIR / "data" / "processed"

print("BASE_DIR:", BASE_DIR)
print("PROCESSED_DIR:", PROCESSED_DIR)

dia = pd.read_csv(
    PROCESSED_DIR / "dia_products.csv"
)

mercadona = pd.read_csv(
    PROCESSED_DIR / "mercadona_products.csv"
)

aldi = pd.read_csv(
    PROCESSED_DIR / "aldi_products.csv"
)
alcampo = pd.read_csv(
    PROCESSED_DIR / "alcampo_products.csv"
)
ahorramas = pd.read_csv(
    PROCESSED_DIR / "ahorramas_products.csv"
)

print("DIA:", len(dia))
print("Mercadona:", len(mercadona))
print("ALDI:", len(aldi))
print("Alcampo:", len(alcampo))
print("AhorraMás:", len(ahorramas))

BASE_DIR: C:\Users\paula\OneDrive\Documentos\uc3m\Cuarto Año\Analitica Web\Supermarket_Project
PROCESSED_DIR: C:\Users\paula\OneDrive\Documentos\uc3m\Cuarto Año\Analitica Web\Supermarket_Project\data\processed
DIA: 917
Mercadona: 895
ALDI: 787
Alcampo: 696
AhorraMás: 393

In [12]:
from normalize import normalize_units

dia = normalize_units(dia)
mercadona = normalize_units(mercadona)
aldi = normalize_units(aldi)
alcampo = normalize_units(alcampo)
ahorramas = normalize_units(ahorramas)

In [13]:
COMMON_COLUMNS = [
    "supermarket",
    "searched_item",
    "name",
    "price",
    "price_per_unit",
    "unit",
]
dia_compare = dia[COMMON_COLUMNS].copy()
mercadona_compare = mercadona[COMMON_COLUMNS].copy()
aldi_compare = aldi[COMMON_COLUMNS].copy()
alcampo_compare = alcampo[COMMON_COLUMNS].copy()
ahorramas_compare = ahorramas[COMMON_COLUMNS].copy()

In [14]:
dia_compare = dia[COMMON_COLUMNS].copy()
mercadona_compare = mercadona[COMMON_COLUMNS].copy()
aldi_compare = aldi[COMMON_COLUMNS].copy()
alcampo_compare = alcampo[COMMON_COLUMNS].copy()
ahorramas_compare = ahorramas[COMMON_COLUMNS].copy()

all_products = pd.concat(
    [
        dia_compare,
        mercadona_compare,
        aldi_compare,
        alcampo_compare,
        ahorramas_compare,
    ],
    ignore_index=True
)

In [15]:
print(
    all_products["supermarket"]
    .value_counts()
)

print("\nUnidades:")
print(
    all_products["unit"]
    .value_counts()
)

print("\nBúsquedas:")
print(
    all_products["searched_item"]
    .value_counts()
)

supermarket
DIA          917
Mercadona    895
ALDI         787
Alcampo      696
AhorraMás    393
Name: count, dtype: int64

Unidades:
unit
KILO         2136
LITRO         836
UNIDAD        152
LAVADO         37
DOCENA         11
METRO           8
ROLLO           4
BOLSITA         4
SERVICIO        2
CAPSULA         2
SOBRE           1
PASTILLA        1
MONODOSIS       1
PANUELO         1
TOALLITA        1
Name: count, dtype: Int64

Búsquedas:
searched_item
leche              616
queso              260
pan                239
pollo              229
pasta              198
aceite             185
agua               175
detergente         175
huevos             171
tomate             160
atún               156
yogur              149
zumo               144
arroz              141
carne picada       132
papel higiénico    129
salmón             127
manzana            109
garbanzos          109
plátano             84
Name: count, dtype: int64

In [16]:
leche = all_products[
    all_products["searched_item"] == "leche"
].copy()

display(
    leche[
        [
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ]
    .sort_values(
        ["unit", "price_per_unit"]
    )
)

,supermarket,name,price,price_per_unit,unit
1877,ALDI,Cápsulas de café con leche,3.17,0.20,CAPSULA
1879,ALDI,Cápsulas de café con leche descafeinado,3.17,0.20,CAPSULA
10,DIA,Huevos medianos M Dia 24 unidades,5.25,2.63,DOCENA
348,DIA,Huevos medianos M de gallinas criadas en suelo...,2.85,2.85,DOCENA
354,DIA,Huevos grandes L Dia 18 unidades,4.39,2.93,DOCENA
...,...,...,...,...,...
3311,AhorraMás,Leche Asturiana 1l desnatada,1.13,NaN,<NA>
3312,AhorraMás,"Leche Pascual Entera 1,5l",1.26,NaN,<NA>
3313,AhorraMás,"Leche Asturiana 1,5l desnatada",1.15,NaN,<NA>
3314,AhorraMás,"Leche Pascual Semi 1,5l",1.19,NaN,<NA>
3315,AhorraMás,Leche Río 1l desnatada,1.02,NaN,<NA>

In [17]:
cheapest_by_supermarket = (
    all_products
    .sort_values("price_per_unit")
    .groupby(
        [
            "searched_item",
            "supermarket",
            "unit",
        ],
        as_index=False
    )
    .first()
)

display(cheapest_by_supermarket)

,searched_item,supermarket,unit,name,price,price_per_unit
0,aceite,ALDI,KILO,Altramuces,1.45,3.82
1,aceite,ALDI,LITRO,Vinagre de vino blanco,0.62,0.62
2,aceite,Alcampo,LITRO,PRODUCTO ALCAMPO Aceite de girasol garrafa de ...,8.55,1.71
3,aceite,DIA,KILO,Sal fina Dia 1 Kg,0.40,0.40
4,aceite,DIA,LITRO,Aceite refinado de girasol Diasol 5 L,8.60,1.72
...,...,...,...,...,...,...
144,zumo,ALDI,LITRO,Bebida Bahamas,1.19,0.60
145,zumo,Alcampo,LITRO,PRODUCTO ALCAMPO Bebida refrescante de zumo de...,1.40,0.70
146,zumo,DIA,LITRO,"Limonada Don Simón 1,5 L",1.35,0.90
147,zumo,Mercadona,KILO,Naranjas,5.85,1.95
148,zumo,Mercadona,LITRO,Bebida Bahamas Hacendado,1.25,0.62

In [18]:
cheapest_overall = (
    all_products
    .sort_values("price_per_unit")
    .groupby(
        [
            "searched_item",
            "unit",
        ],
        as_index=False
    )
    .first()
)

display(
    cheapest_overall[
        [
            "searched_item",
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ]
)

,searched_item,supermarket,name,price,price_per_unit,unit
0,aceite,Mercadona,Sal gruesa Hacendado,0.40,0.40,KILO
1,aceite,ALDI,Vinagre de vino blanco,0.62,0.62,LITRO
2,aceite,Mercadona,Tortas de aceite Inés Rosales,2.15,0.36,UNIDAD
3,agua,DIA,Aguacate bandeja 450 g,1.79,3.98,KILO
4,agua,Mercadona,Agua mineral grande Aguadoy,0.95,0.12,LITRO
...,...,...,...,...,...,...
60,tomate,Mercadona,Pizzas tomate y queso Hacendado ultracongeladas,2.40,1.20,UNIDAD
61,yogur,Mercadona,Yogur sabores Hacendado,2.40,1.20,KILO
62,yogur,Mercadona,Salsa Yogur Hacendado,1.20,3.87,LITRO
63,zumo,Mercadona,Naranjas,5.85,1.95,KILO
64,zumo,ALDI,Bebida Bahamas,1.19,0.60,LITRO

In [19]:
display(
    all_products[
        all_products["searched_item"] == "leche"
    ][
        [
            "supermarket",
            "name",
            "price",
            "price_per_unit",
            "unit",
        ]
    ].head(50)
)

,supermarket,name,price,price_per_unit,unit
0,DIA,Leche semidesnatada Dia Láctea pack 6 x 1 L,5.04,0.84,LITRO
1,DIA,Leche entera Dia Láctea pack 6 x 1 L,5.76,0.96,LITRO
2,DIA,Leche semidesnatada sin lactosa Dia Láctea pac...,5.34,0.89,LITRO
3,DIA,Leche semidesnatada Dia Láctea 1 L,0.84,0.84,LITRO
4,DIA,Leche desnatada Dia Láctea pack 6 x 1 L,4.92,0.82,LITRO
5,DIA,Leche entera Dia Láctea 1 L,0.96,0.96,LITRO
6,DIA,Leche desnatada sin lactosa Dia Láctea pack 6 ...,5.10,0.85,LITRO
7,DIA,Leche semidesnatada sin lactosa Dia Láctea 1 L,0.89,0.89,LITRO
8,DIA,Leche entera Dia Láctea 3 x 200 ml,0.92,1.53,LITRO
9,DIA,Leche semidesnatada Asturiana pack 6 x 1 L,6.54,1.09,LITRO
10,DIA,Huevos medianos M Dia 24 unidades,5.25,2.63,DOCENA
11,DIA,Leche entera Asturiana pack 6 x 1 L,7.44,1.24,LITRO
12,DIA,Leche desnatada Dia Láctea 1 L,0.82,0.82,LITRO
13,DIA,Leche entera pasteurizada Dia Láctea 1 L,1.15,1.15,LITRO
14,DIA,Leche semidesnatada Dia Láctea botella 1.5 L,1.45,0.97,LITRO
15,DIA,Leche entera sin lactosa Dia Láctea pack 6 x 1 L,5.94,0.99,LITRO
16,DIA,Leche entera Dia Láctea botella 1.5 L,1.56,1.04,LITRO
17,DIA,Batido de cacao 90% leche Dia Láctea 6 x 200 ml,1.75,1.46,LITRO
18,DIA,Leche semidesnatada sin lactosa Asturiana pack...,8.22,1.37,LITRO
19,DIA,Leche semidesnatada Asturiana pack 6 x 1.5 L,10.74,1.19,LITRO
20,DIA,Leche entera Asturiana pack 6 x 1.5 L,11.82,1.31,LITRO
21,DIA,Leche semidesnatada sin lactosa Dia Láctea 3 x...,0.95,1.58,LITRO
22,DIA,Leche desnatada sin lactosa Dia Láctea 1 L,0.85,0.85,LITRO
23,DIA,Leche semidesnatada pasteurizada Dia Láctea 1 L,1.09,1.09,LITRO
24,DIA,Bebida de avena Dia Vegedia 1 L,0.95,0.95,LITRO
25,DIA,Leche entera sin lactosa Dia Láctea 1 L,0.99,0.99,LITRO
26,DIA,Nata para cocinar textura espesa Dia Láctea 50...,1.55,3.10,LITRO
27,DIA,Leche entera Dia Láctea pack 6 x 1.5 L,9.36,1.04,LITRO
28,DIA,Leche desnatada Asturiana pack 6 x 1 L,6.36,1.06,LITRO
29,DIA,Leche semidesnatada Dia Láctea pack 6 x 1.5 L,8.70,0.97,LITRO
30,DIA,Leche semidesnatada Asturiana pack 6 x 2.2 L,14.28,1.08,LITRO
31,DIA,Leche entera Asturiana 1 L,1.24,1.24,LITRO
32,DIA,Leche semidesnatada calcio Dia Láctea pack 6 x...,6.30,1.05,LITRO
33,DIA,Leche semidesnatada Asturiana 1 L,1.09,1.09,LITRO
34,DIA,Leche condensada Dia Láctea 450 g,2.35,5.22,KILO
35,DIA,Arroz con leche Dia Caprichoso 4 x 125 g,1.25,2.50,KILO
36,DIA,Leche condensada Dia Láctea 1 Kg,3.35,3.35,KILO
37,DIA,Nata para cocinar 18% M.G. Dia Láctea 3 x 200 ml,1.85,3.08,LITRO
38,DIA,Leche desnatada sin lactosa alta en proteínas ...,1.35,1.35,LITRO
39,DIA,Mousse de chocolate con leche Dia Caprichoso 4...,1.15,4.79,KILO
40,DIA,Galletas cubiertas de chocolate con leche Gall...,1.35,9.00,KILO
41,DIA,Leche entera Pascual pack 6 x 1 L,8.34,1.39,LITRO
42,DIA,Leche desnatada sin lactosa Asturiana 1 L,1.33,1.33,LITRO
43,DIA,Chocolate con leche Nestlé Extrafino 125 g,1.50,12.00,KILO
44,DIA,Pan de leche El Molino de Dia 350 g,1.35,3.86,KILO
45,DIA,Bebida de almendras 0% azúcares Dia Vegedia 1 L,1.49,1.49,LITRO
46,DIA,Leche semidesnatada Pascual pack 6 x 1 L,8.10,1.35,LITRO
47,DIA,Leche semidesnatada Lauki pack 6 x 1 L,6.54,1.09,LITRO
48,DIA,Leche desnatada Asturiana pack 6 x 1.5 L,10.38,1.15,LITRO
49,DIA,Leche desnatada Pascual 1 L,1.29,1.29,LITRO